### ISSUE TITLE
Karaoke mode doesn't match song position

### ISSUE THREAD

**Issue by bradydowling** [gedrick/SpotifyKaraoke#9]
Sometimes the scrolling doesn't quite keep up with the pace of the song. In these cases, it would be helpful to allow the user to scroll to the point in the song that's relevant.

This is technically possible but it looks like the autoscrolling is going to an **absolute** percentage of the page based on the progress of the song, which essentially nullifies the user's scrolling after a second or two.

## Potential solutions
There isn't a perfect solution to this (without extensive work) but the following could help:
- Scroll relative to the current page's scroll position. This would allow the user to scroll to catch up to where the lyrics actually are and then the (dumb) autoscroller just attempts to scroll from that point in the song.
- Add some buffer to the start of each song before you begin autoscroll to account for some intro time. You never know if a song has an intro before the lyrics start or how long that would be but a short buffer could be safe and helpful.
- Add padding at the end of the song so autoscroll gets to the end of the page several seconds before the end of the song. If you're at the bottom of the page, you should still be able to see the previous 10-20 lines of lyrics so you're safe to be sitting at the bottom for a certain period of time.

## Workaround
Decrease the font size in your browser 😄 

## Steps to reproduce
**Song:** Stitches - Seeb Remix (Shawn Mendes, Seeb)
**OS:** macOS (15" Macbook Pro)
**Browser:** Firefox Developer Edition (77.0b3)

**Comment by gedrick** [comment]
Hi there Brady - thanks for filing this issue and for the suggestions, apologies for the super late reply. I finally got some time to take a look at this again. I had some trouble coming up with a good way of handling the lyric scrolling, but was never quite satisfied with it, but this seems like it may be a good solution. I did add a ton of padding to the end of the lyrics container as they were getting cut off pretty badly, but adjusting this is my next target.

I think this can help get this working properly:
* While a user is scrolling the lyrics manually, disable lyric scrollTop changing
* When a new song comes in, load in the lyrics and calculate the height of the container vs. the duration of the song (in seconds), divided _that_ by the delay between song status pulls (2 seconds I believe) to figure out the per-second "adjustment" to make to the scrollTop position/
* Do away with adjusting the scroll position only after API calls, and replace it with a smooth scroll 👍 

This will take some time (mostly in finding time), but if you have any more ideas for improvements, please don't hesitate to share, or submit a PR if you are so inclined :) Thanks again!

**Comment by gedrick** [comment]
Just an FYI, I updated the app today with a "relative scroll" feature, rather than a relative scroll. It also has a few other QoL changes that should improve the overall experience. Thanks again for your interest and suggestions :+1:

**Comment by bradydowling** [comment]
Awesome, thank you for this!
